### ISSUE TITLE
self.store.sort(lambda a, b: a.name > b.name)

### ISSUE THREAD

**Issue by Framelony** [timlau/yumex-ng#21]
yumex 

(yumex:3686936): Gtk-WARNING **: 18:49:27.661: Theme parser error: style.css:132:14-16: 'x' is not a valid unit

(yumex:3686936): Gtk-WARNING **: 18:49:27.661: Theme parser error: style.css:149:1-2: Expected a valid selector
18:49:27 DEBUG : (yumex) -   commmand-line : Namespace(debug=False, exit=False)
18:49:29 CRITICAL: (root ) -  Uncaught exception: '>' not supported between instances of 'str' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                 ^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'NoneType'
Adwaita-Message: 18:49:29.115: AdwMessageDialog mapped without a transient parent. This is discouraged.
18:49:29 CRITICAL: (root ) -  Uncaught exception: '>' not supported between instances of 'str' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                 ^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'NoneType'
Adwaita-Message: 18:49:29.134: AdwMessageDialog mapped without a transient parent. This is discouraged.

(yumex:3686936): Gtk-WARNING **: 18:49:29.306: Failed to set text 'Online video & audio downloader for Linux, 1300+ websites support' from markup due to error parsing markup: Errore alla riga 1: L'entità non termina con un punto e virgola; probabilmente è stata utilizzata una "e commerciale" senza l'intento di iniziare una entità — usare &amp;
18:49:29 CRITICAL: (root ) -  Uncaught exception: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 192, in on_row_bind
    row.set_subtitle(pkg.summary)
TypeError: Argument 1 does not allow None as a value

thanks for your work  yumex is a great tool

**Comment by timlau** [comment]
Thanks for reporting, I will look into it

**Comment by timlau** [comment]
It was a problem with some flatpaks, there don't have appdata and the flatpak API returns None and that break the sorting in the view.
I have fixed it so the ui  always get a string back.

You cant test from git checkout  or the latest COPR packages.

**Comment by Framelony** [comment]
still don't completly solved yet 

thanks 
F. 


yumex 
14:03:05 DEBUG : (yumex) -  Version:  4.99.2-git20230117 (DNF4)
14:03:05 DEBUG : (yumex) -  executable : /usr/bin/yumex
14:03:05 DEBUG : (yumex) -  commmand-line : Namespace(debug=False, exit=False)
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.317: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.331: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.344: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.368: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.396: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.414: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                          ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.427: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:07 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 351, in wrap
    return func(a, b, *user_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 57, in <lambda>
    self.store.sort(lambda a, b: a.name > b.name)
                                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:07.439: AdwMessageDialog mapped without a transient parent. This is discouraged.

(yumex:329053): Gtk-WARNING **: 14:03:07.633: Failed to set text 'Online video & audio downloader for Linux, 1300+ websites support' from markup due to error parsing markup: Errore alla riga 1: L'entità non termina con un punto e virgola; probabilmente è stata utilizzata una "e commerciale" senza l'intento di iniziare una entità — usare &amp;
14:03:08 CRITICAL: (yumex) -  Uncaught exception: 'FlatpakPackage' object has no attribute 'log'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 191, in on_row_bind
    row.set_title(f"{pkg.name} - {pkg.version}")
                     ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/__init__.py", line 45, in name
    self.log(f"flatpak {id} don't have an appname, using {name}")
    ^^^^^^^^
AttributeError: 'FlatpakPackage' object has no attribute 'log'
Adwaita-Message: 14:03:08.124: AdwMessageDialog mapped without a transient parent. This is discouraged.
14:03:08 DEBUG : (yumex) -  search changed : 
14:03:08 DEBUG : (yumex) -  Loading packages : installed
14:03:08 DEBUG : (dnf  ) -  User-Agent: constructed: 'libdnf (Fedora Linux 37; workstation; Linux.x86_64)'
14:03:08 DEBUG : (yumex) -  >> Running async job : get_packages_by_filter.
14:03:08 DEBUG : (dnf  ) -  User-Agent: constructed: 'libdnf (Fedora Linux 37; workstation; Linux.x86_64)'
14:03:08 DEBUG : (dnf  ) -  repository: uso della cache per anydesk
14:03:08 DEBUG : (dnf  ) -  anydesk: usando metadati di mer 2 nov 2022, 16:48:25.
14:03:08 DEBUG : (dnf  ) -  repository: uso della cache per copr:copr.fedorainfracloud.org:timlau:yumex-ng
14:03:08 DEBUG : (dnf  ) -  copr:copr.fedorainfracloud.org:timlau:yumex-ng: usando metadati di dom 15 gen 2023, 09:45:45.
14:03:08 DEBUG : (dnf  ) -  repository: uso della cache per phracek-PyCharm
14:03:08 DEBUG : (dnf  ) -  phracek-PyCharm: usando metadati di ven 30 dic 2022, 12:01:04.
14:03:08 DEBUG : (dnf  ) -  repository: uso della cache per docker-ce-stable
14:03:08 DEBUG : (dnf  ) -  docker-ce-stable: usando metadati di lun 9 gen 2023, 20:19:10.
14:03:08 DEBUG : (dnf  ) -  repository: uso della cache per fedora
14:03:09 DEBUG : (dnf  ) -  fedora: usando metadati di gio 10 nov 2022, 10:30:00.
14:03:09 DEBUG : (dnf  ) -  repository: uso della cache per fedora-cisco-openh264
14:03:09 DEBUG : (dnf  ) -  fedora-cisco-openh264: usando metadati di gio 6 ott 2022, 13:01:40.
14:03:09 DEBUG : (dnf  ) -  repository: uso della cache per fedora-modular
14:03:09 DEBUG : (dnf  ) -  fedora-modular: usando metadati di gio 10 nov 2022, 10:23:24.
14:03:09 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Updates started
14:03:09 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Updates completed
14:03:09 DEBUG : (dnf  ) -  riattivazione: non riuscita per 'updates', checksum sha256 non corrispondente.
14:03:09 DEBUG : (dnf  ) -  repo: download da remoto: updates
14:03:11 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Updates completed
14:03:13 DEBUG : (dnf  ) -  updates: usando metadati di mar 17 gen 2023, 02:24:57.
14:03:13 DEBUG : (yumex) -   --> progress: Fedora Modular 37 - x86_64 - Updates started
14:03:14 DEBUG : (yumex) -   --> progress: Fedora Modular 37 - x86_64 - Updates completed
14:03:14 DEBUG : (dnf  ) -  riattivazione: 'updates-modular' può essere riattivato - il checksum del metalink corrisponde.
14:03:14 DEBUG : (dnf  ) -  updates-modular: usando metadati di mar 3 gen 2023, 02:27:52.
14:03:14 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Test Updates started
14:03:15 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Test Updates completed
14:03:15 DEBUG : (dnf  ) -  riattivazione: non riuscita per 'updates-testing', checksum sha256 non corrispondente.
14:03:15 DEBUG : (dnf  ) -  repo: download da remoto: updates-testing
14:03:16 DEBUG : (yumex) -   --> progress: Fedora 37 - x86_64 - Test Updates completed
14:03:17 DEBUG : (dnf  ) -  updates-testing: usando metadati di mar 17 gen 2023, 03:32:22.
14:03:17 DEBUG : (yumex) -   --> progress: Fedora Modular 37 - x86_64 - Test Updates started
14:03:17 DEBUG : (yumex) -   --> progress: Fedora Modular 37 - x86_64 - Test Updates completed
14:03:17 DEBUG : (dnf  ) -  riattivazione: 'updates-testing-modular' può essere riattivato - il checksum del metalink corrisponde.
14:03:17 DEBUG : (dnf  ) -  updates-testing-modular: usando metadati di lun 26 dic 2022, 02:33:04.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per google-chrome
14:03:17 DEBUG : (dnf  ) -  google-chrome: usando metadati di ven 13 gen 2023, 00:37:17.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per jami
14:03:17 DEBUG : (dnf  ) -  jami: usando metadati di ven 13 gen 2023, 20:01:40.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per pgAdmin4
14:03:17 DEBUG : (dnf  ) -  pgAdmin4: usando metadati di mar 20 dic 2022, 14:58:01.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-free
14:03:17 DEBUG : (dnf  ) -  rpmfusion-free: usando metadati di ven 11 nov 2022, 17:54:42.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-free-updates
14:03:17 DEBUG : (dnf  ) -  rpmfusion-free-updates: usando metadati di ven 13 gen 2023, 15:27:21.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-free-updates-testing
14:03:17 DEBUG : (dnf  ) -  rpmfusion-free-updates-testing: usando metadati di ven 13 gen 2023, 15:31:39.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-nonfree
14:03:17 DEBUG : (dnf  ) -  rpmfusion-nonfree: usando metadati di ven 11 nov 2022, 18:25:12.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-nonfree-nvidia-driver
14:03:17 DEBUG : (dnf  ) -  rpmfusion-nonfree-nvidia-driver: usando metadati di ven 13 gen 2023, 16:06:15.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-nonfree-steam
14:03:17 DEBUG : (dnf  ) -  rpmfusion-nonfree-steam: usando metadati di mer 24 ago 2022, 18:15:54.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-nonfree-updates
14:03:17 DEBUG : (dnf  ) -  rpmfusion-nonfree-updates: usando metadati di ven 13 gen 2023, 15:54:51.
14:03:17 DEBUG : (dnf  ) -  repository: uso della cache per rpmfusion-nonfree-updates-testing
14:03:17 DEBUG : (dnf  ) -  rpmfusion-nonfree-updates-testing: usando metadati di ven 13 gen 2023, 15:55:19.
14:03:18 DEBUG : (dnf  ) -  repository: uso della cache per teamviewer
14:03:18 DEBUG : (dnf  ) -  teamviewer: usando metadati di gio 15 dic 2022, 08:13:34.
14:03:18 DEBUG : (dnf  ) -  repository: uso della cache per code
14:03:18 DEBUG : (dnf  ) -  code: usando metadati di lun 16 gen 2023, 16:02:39.
14:03:18 DEBUG : (yumex) -  << Completed async job : get_packages_by_filter.
14:03:18 DEBUG : (yumex) -  >> starting add_packages_to_store
14:03:18 DEBUG : (yumex) -  Adding packages to store
14:03:18 DEBUG : (yumex) -   --> sorting by : name
14:03:19 DEBUG : (yumex) -   --> number of packages : 2576
14:03:19 DEBUG : (yumex) -  << add_packages_to_store took 0.0969 sec
14:03:19 DEBUG : (yumex) -  >> Running async job : get_package_info.
14:03:19 DEBUG : (yumex) -   DNF4: dnf_pkg: aajohan-comfortaa-fonts-3.101-5.fc37.noarch attribute : description
14:03:19 DEBUG : (yumex) -  << Completed async job : get_package_info.

**Comment by timlau** [comment]
fixed the Typo and made new copr builds

**Comment by Framelony** [comment]
perfect! thanks
