### ISSUE TITLE
Crashes before application launched

### ISSUE THREAD

**Issue by Spaceboy60** [timlau/yumex-ng#53]
11:36:35 DEBUG : (yumex) -  Version:  4.99.4-git20240409 (DNF5)
11:36:35 DEBUG : (yumex) -  executable : /usr/bin/yumex
11:36:35 DEBUG : (yumex) -  commmand-line : Namespace(debug=False, exit=False)

(yumex:103903): Gtk-WARNING **: 11:36:35.742: Unable to acquire session bus: Failed to execute child process “dbus-launch” (No such file or directory)
11:36:35 CRITICAL: (yumex) -  Uncaught exception: 'XDG_DATA_DIRS'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yumex/main.py", line 59, in do_activate
    self.win = YumexMainWindow(
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/ui/window.py", line 78, in __init__
    self.setup_gui()
  File "/usr/lib/python3.12/site-packages/yumex/ui/window.py", line 106, in setup_gui
    self.setup_flatpaks()
  File "/usr/lib/python3.12/site-packages/yumex/ui/window.py", line 109, in setup_flatpaks
    self.flatpak_view = YumexFlatpakView(self.presenter)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_view.py", line 41, in __init__
    self.icons_paths = self.get_icon_paths()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_view.py", line 68, in get_icon_paths
    return [f"{path}/icons/" for path in os.environ["XDG_DATA_DIRS"].split(":")]
                                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'XDG_DATA_DIRS'
11:36:35 DEBUG : (yumex) -  traceback written to /root/.local/share/yumex/traceback_04-15-2024_113635.txt
Adwaita-Message: 11:36:35.907: AdwMessageDialog mapped without a transient parent. This is discouraged.
11:36:36 DEBUG : (yumex) -  search changed :

**Comment by timlau** [comment]
Should be fixed in the 4.99.5-0.1.git20240417 builld

```
sudo dnf5 update yumex-dnf5 --refresh
```

**Comment by Spaceboy60** [comment]
same issue still:

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6146:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6154:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6217:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6222:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6341:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.371: Theme parser error: gtk-dark.css:6346:10-13: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.375: Theme parser error: gtk-dark.css:7084:21-28: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.375: Theme parser error: gtk-dark.css:7089:21-28: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.376: Theme parser error: gtk-dark.css:7243:21-28: Expected a valid color.

(process:118278): Gtk-WARNING **: 15:01:46.376: Theme parser error: gtk-dark.css:7249:21-28: Expected a valid color.

(process:118278): Adwaita-WARNING **: 15:01:46.409: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
15:01:46 DEBUG : (yumex) -  Version:  4.99.4-git20240417 (DNF5)
15:01:46 DEBUG : (yumex) -  executable : /usr/bin/yumex
15:01:46 DEBUG : (yumex) -  commmand-line : Namespace(debug=False, exit=False)
15:01:47 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False 
15:01:47 DEBUG : (yumex) -  window-height: 700
15:01:47 DEBUG : (yumex) -  window-width: 1000
15:01:47 DEBUG : (yumex) -  fullscreened: False
15:01:47 DEBUG : (yumex) -  maximized: False
15:01:47 DEBUG : (yumex) -  SIGNAL: emit package-filter-changed: installed
15:01:47 DEBUG : (yumex) -  SIGNAL: package filter changed : installed
15:01:47 DEBUG : (yumex) -  Loading packages : installed
15:01:47 DEBUG : (yumex) -  >> Running async job : get_packages_by_filter.
15:01:47 DEBUG : (yumex) -  search changed : 
15:01:47 DEBUG : (yumex) -  Error while running async job: <bound method YumexPresenter.get_packages_by_filter of <yumex.backend.presenter.YumexPresenter object at 0x7f05dd0e32f0>>
Exception: 'Backend' object has no attribute 'load_config_from_file'
  File "/usr/lib/python3.12/site-packages/yumex/utils/__init__.py", line 73, in target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/presenter.py", line 125, in get_packages_by_filter
    return self.package_cache.get_packages_by_filter(pkgfilter, reset)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/presenter.py", line 83, in package_cache
    self._cache: PackageCache = YumexPackageCache(backend=self.package_backend)
                                                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/presenter.py", line 69, in package_backend
    self._backend: PackageBackend = self.dnf_backend_factory.get_backend()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/dnf/factory.py", line 15, in get_backend
    return self.get_dnf5_backend()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/dnf/factory.py", line 34, in get_dnf5_backend
    return Dnf5Backend(self.presenter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/dnf/dnf5.py", line 92, in __init__
    self.load_config_from_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
15:01:47 DEBUG : (yumex) -  << Completed async job : get_packages_by_filter.
15:01:47 DEBUG : (yumex) -  Window: package selection changed : None

**Comment by timlau** [comment]
https://github.com/timlau/yumex-ng/commit/660de44c747d7d92466ade6c6445a5405ffff8a8

**Comment by timlau** [comment]
fixed in 4.99.4-git20240421 (DNF5) builds in copr.

**Comment by timlau** [comment]
what version of of dnf5 are you running, the dnf5 deprecation triggering this error, should not be released yet ?

**Comment by Spaceboy60** [comment]
5.1.17

**Comment by Spaceboy60** [comment]
Working (to an extent) now. At least it opens without issue.
